# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 12:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('first_goals', models.PositiveIntegerField(default=0)),
                ('second_goals', models.PositiveIntegerField(default=0)),
                ('tour', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
                ('play_off', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(db_index=True, max_length=40)),
                ('date_of_reg', models.DateField(auto_now=True)),
                ('position', models.IntegerField(blank=True, choices=[(0, 'Goalkeeper'), (1, 'Central base'), (2, 'Left base'), (3, 'Right base'), (4, 'Defending midfielder'), (5, 'Central midfielder'), (6, 'Left midfielder'), (7, 'Right midfielder'), (8, 'Atacking midfielder'), (9, 'Striker'), (10, 'Left forward'), (11, 'Right forward')], null=True)),
                ('platform', models.CharField(choices=[('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('XB', 'Xbox 360'), ('PC', 'PC'), ('Real', 'Real')], max_length=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('t_adm', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=40)),
                ('Date_of_creation', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('PS3', 'PlayStation 3'), ('PS4', 'PlayStation 4'), ('XB', 'Xbox 360'), ('PC', 'PC'), ('Real', 'Real')], max_length=4)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('first_place_rew', models.PositiveIntegerField(default=0)),
                ('second_place_rew', models.PositiveIntegerField(default=0)),
                ('straight_up', models.PositiveIntegerField(default=0)),
                ('straight_down', models.PositiveIntegerField(default=0)),
                ('third_place_rew', models.PositiveIntegerField(default=0)),
                ('stik_up', models.PositiveIntegerField(default=0)),
                ('stik_down', models.PositiveIntegerField(default=0)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TTD_player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0)),
                ('assists', models.PositiveIntegerField(default=0)),
                ('shots', models.PositiveIntegerField(default=0)),
                ('shots_on_target', models.PositiveIntegerField(default=0)),
                ('passes_try', models.PositiveIntegerField(default=0)),
                ('passes', models.PositiveIntegerField(default=0)),
                ('tackles', models.PositiveIntegerField(default=0)),
                ('tackles_won', models.PositiveIntegerField(default=0)),
                ('interceptions', models.PositiveIntegerField(default=0)),
                ('saves', models.PositiveIntegerField(default=0)),
                ('drib_try', models.PositiveIntegerField(default=0)),
                ('drib', models.PositiveIntegerField(default=0)),
                ('bend_try', models.PositiveIntegerField(default=0)),
                ('bend', models.PositiveIntegerField(default=0)),
                ('TTD', models.PositiveIntegerField(default=0)),
                ('TTD_suc', models.PositiveIntegerField(default=0)),
                ('position', models.IntegerField(choices=[(0, 'Goalkeeper'), (1, 'Central base'), (2, 'Left base'), (3, 'Right base'), (4, 'Defending midfielder'), (5, 'Central midfielder'), (6, 'Left midfielder'), (7, 'Right midfielder'), (8, 'Atacking midfielder'), (9, 'Striker'), (10, 'Left forward'), (11, 'Right forward')])),
                ('own_goal', models.PositiveIntegerField(default=0)),
                ('yellow', models.PositiveIntegerField(default=0)),
                ('red', models.PositiveIntegerField(default=0)),
                ('rating_1', models.IntegerField(default=5)),
                ('rating_2', models.IntegerField(default=5)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Player')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='tournam',
            field=models.ManyToManyField(to='first.Tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='first.Team'),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sec', to='first.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='tourn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Tournament'),
        ),
        migrations.AddField(
            model_name='img',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Match'),
        ),
        migrations.AddField(
            model_name='event',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Match'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('login', 'platform')]),
        ),
    ]
