# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
