# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='player_item',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='player_item',
            name='player',
        ),
        migrations.RemoveField(
            model_name='player_item',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='player',
        ),
        migrations.RemoveField(
            model_name='ttd_player',
            name='rating',
        ),
        migrations.AddField(
            model_name='tournament',
            name='straight_down',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='straight_up',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ttd_player',
            name='rating_1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttd_player',
            name='rating_2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='img',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Player_item',
        ),
    ]
