# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='second_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='first.Team'),
            preserve_default=False,
        ),
    ]
