# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first', '0002_auto_20161013_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('Date_of_reg', models.DateField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
        ),
    ]
