# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0002_auto_20161020_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='player',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='cap',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='first.Player'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together=set([('login', 'platform')]),
        ),
    ]
