# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_match_second_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='second_team',
        ),
    ]
