# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_remove_match_second_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='first_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='cap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.Player'),
        ),
    ]
