# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 15:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0003_auto_20161104_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(blank=True, choices=[(0, 'Goalkeeper'), (1, 'Central base'), (2, 'Left base'), (3, 'Right base'), (4, 'Defending midfielder'), (5, 'Central midfielder'), (6, 'Left midfielder'), (7, 'Right midfielder'), (8, 'Atacking midfielder'), (9, 'Striker'), (10, 'Left forward'), (11, 'Right forward'), (12, 'Нет')], default=12),
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.ManyToManyField(to='first.Tag'),
        ),
    ]
