# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('Date_of_creation', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('cap', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first.Player')),
            ],
        ),
    ]
