# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.Team')),
                ('second_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='first.Team')),
            ],
        ),
    ]
