# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_auto_20161013_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='first_team',
        ),
        migrations.AlterField(
            model_name='team',
            name='cap',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='first.Player'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
