# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(blank=True, choices=[(0, 'Goalkeeper'), (1, 'Central base'), (2, 'Left base'), (3, 'Right base'), (4, 'Defending midfielder'), (5, 'Central midfielder'), (6, 'Left midfielder'), (7, 'Right midfielder'), (8, 'Atacking midfielder'), (9, 'Striker'), (10, 'Left forward'), (11, 'Right forward'), (12, 'Нет')], default=12),
        ),
    ]
