# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_auto_20161013_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Фамилия'),
        ),
    ]
